name: studio-nuxt-build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add write workflow permissions
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Identify package manager
        id: pkgman
        run: |
          if [ -f "./pnpm-lock.yaml" ]; then
            echo "package_manager=pnpm" >> $GITHUB_ENV
          elif [ -f "./package-lock.json" ]; then
            echo "package_manager=npm" >> $GITHUB_ENV
          elif [ -f "./yarn.lock" ]; then
            echo "package_manager=yarn" >> $GITHUB_ENV
          else
            echo "package_manager=pnpm" >> $GITHUB_ENV
          fi
          echo "cache=$package_manager" >> $GITHUB_ENV

      - name: Install pnpm
        if: ${{ env.package_manager == 'pnpm' }}
        run: npm install -g pnpm

      - uses: actions/setup-node@v4
        with:
          version: ${{ matrix.node }}
          cache: ${{ env.cache }}

      - name: Install dependencies
        run: ${{ env.package_manager }} install

      - name: Install @nuxthq/studio
        run: ${{ env.package_manager }} add -D @nuxthq/studio

      - name: Create .nuxtrc
        run: echo $'\nautoImport=true\nmodules[]=@nuxthq/studio' >> .nuxtrc

      - name: Generate
        run: npx nuxi build --preset github_pages
        env:
          NUXT_PUBLIC_STUDIO_API_URL: https://api.nuxt.studio
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

      # Deployment job
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./.output/public
